### ISSUE TITLE
[Bug] Contributors not filtering by repository

### ISSUE THREAD

**Issue by via-justa** [grafana/github-datasource#190]
Plugin version: `1.3.0`
Grafana Version: `9.2.5`
Token Permissions: 
```
repo
read:packages
read:user
read::email
read:project
```
The query for contributors does not filter the results by repository. 
![Screenshot 2022-12-02 at 08 37 17](https://user-images.githubusercontent.com/25720282/205241431-8d56b770-794d-4bcc-90b0-75cbf0b9b050.png)
![Screenshot 2022-12-02 at 08 37 46](https://user-images.githubusercontent.com/25720282/205241442-0ca9895b-c175-4244-a541-28dd650b51c2.png)

**Comment by andresako** [comment]
Bump for this :)

**Comment by via-justa** [comment]
Few versions later and still no word on the topic

**Comment by gwdawson** [comment]
Hey, thank you for creating this issue.

Due to limitations with the GitHub GraphQL API, we are unable to directly retrieve a list of contributors for a specific repository.

As a workaround, we are querying for mentionableUsers which includes everyone who has interacted with the repository and also and all members of the organization owning that repo.

this means that unfortunately the response can be populated by people who indeed haven't directly contributed, especially if owned by a github organization.

**Comment by julioz** [comment]
@gwdawson Thanks for the explanation, I hit the same question when setting up this data source and [importing the dashboard provided](https://github.com/grafana/github-datasource/blob/main/src/dashboards/dashboard.json). Can I suggest you update the "contributors" panel to include a description that at least mentions this limitation? As of now, it's pretty confusing to see names for people who didn't push a single commit to the selected repository in the dashboards.

cc @ivanahuckova since it looks like you are an active contributor to this repo too. Hope it's not too much noise for you :)
