### ISSUE TITLE
Listing repositories doesn't find all of them

### ISSUE THREAD

**Issue by maximbaz** [grafana/github-datasource#59]
This is a follow-up to #52, I tested creating a dashboard variable for repositories of my team within the organization (using regex `/^myteam-.*/`), and I noticed that the resulting variable doesn't contain all of our repos. 

I think it's simply because our organization has more than 1.5k repos currently, and I presume that the current approach limits the amount of repos it can return.

Let me know if you need some extra info and I will try to collect it for you 🙂

**Comment by kminehart** [comment]
That's a lot! Luckily that probably doesn't change very much.

GitHub access tokens have a limit of 5,000 requests per 30 minutes. Everything is listed in pages of 100, so I tried to set a limit on the number of pages pretty low since people will very easily max out their tokens, especially in shared environments.

I can remove the limit on Repositories since they're only used in variables, and maybe increase the cache timeout on Repositories to 30 minutes or so.
