### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by subnova-etsy** [grafana/github-datasource#75]
The underlying GitHub library includes support for GitHub Enterprise (https://github.com/shurcooL/githubv4#authentication). Adding support should consist of adding an option to configure the GitHub Enterprise URL and creating the Enterprise Client when this is set.

**Comment by bmike78** [comment]
https://github.com/grafana/github-datasource/pull/77

This worked for my on my instance of Github Enterprise.

**Comment by bmike78** [comment]
Thanks for merging.

Upon further testing, I noticed is that pull requests are not showing up because my version of Github Enterprise does not have Pull Request Drafts enabled.  I'm circling back with my GitHub Enterprise admin to see if that feature can be enabled.

This should be a feature available in newer releases:
https://enterprise.github.com/releases/2.17.0/notes

**Comment by bmike78** [comment]
Just an additional note that an upgrade to Github Enterprise 2.22 seemed to resolve the issue with the dashboard failing on Pull Request Drafts.
